package com.routeoptimizer.service;
 
import com.routeoptimizer.external.GeminiClient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.routeoptimizer.model.entity.Batch;
import com.routeoptimizer.model.entity.Order;

import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Asesor Contextual Inteligente — el "Estratega" del sistema.
 * 
 * Orquesta prompts para Google Gemini según 3 casos de uso:
 * 1. Pre-ruta: Analiza lote + tráfico → genera recomendación de ruta
 * 2. Desvío: Detecta desviación → genera instrucción para retomar ruta
 * 3. Resumen: Analiza jornada → genera resumen del día
 */
@Service
public class ContextualAdvisor {

  private static final Logger log = LoggerFactory.getLogger(ContextualAdvisor.class);
  private final GeminiClient geminiClient;

  public ContextualAdvisor(GeminiClient geminiClient) {
    this.geminiClient = geminiClient;
  }

  /**
   * CASE A — Pre-route: Generates an intelligent recommendation BEFORE the driver
   * leaves.
   * Analyzes the complete batch context: number of orders, zone, traffic,
   * client notes and time of day.
   *
   * @param batch        The batch of orders to analyze
   * @param trafficData  Real-time traffic data from MLModelAdapter
   * @param urgentOrders Number of orders marked as high-priority
   * @return Natural language recommendation generated by Gemini
   */
  public String generatePreRouteRecommendation(Batch batch, Map<String, Double> trafficData, long urgentOrders) {
    List<Order> orders = batch.getOrders();
    String hour = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm"));
    double congestion = trafficData.getOrDefault("congestion_factor", 0.0);
    double closures = trafficData.getOrDefault("road_closures", 0.0);

    String city = orders.stream()
        .filter(p -> p.getCity() != null)
        .map(Order::getCity)
        .findFirst()
        .orElse("Bogotá");

    String addresses = orders.stream()
        .limit(5)
        .map(p -> String.format("- %s (%s, priority: %s)",
            p.getAddress(), p.getCity(), p.getPriority()))
        .collect(Collectors.joining("\n"));

    String clientNotes = orders.stream()
        .filter(p -> p.getClientReference() != null && !p.getClientReference().isBlank())
        .limit(3)
        .map(p -> String.format("- Order #%d (%s): \"%s\"", p.getId(), p.getAddress(), p.getClientReference()))
        .collect(Collectors.joining("\n"));

    String prompt = String.format("""
        Eres el asistente logístico de VibeRoute Colombia. Analiza este lote de entregas y genera
        una recomendación CORTA (máximo 3 oraciones) para el repartidor.

        CONTEXTO:
        - Ciudad: %s
        - Hora actual: %s
        - Total de pedidos: %d
        - Pedidos urgentes (prioridad ALTA): %d
        - Factor de congestión: %d%% (0%% = sin tráfico, 100%% = tráfico total)
        - Cierres viales reportados: %s

        PRIMERAS DIRECCIONES DEL LOTE:
        %s

        %s

        Responde en español colombiano, de forma profesional y directa.
        NO uses emojis. NO repitas los datos que te di. Solo da la recomendación.
        """,
        city,
        hour,
        orders.size(),
        urgentOrders,
        (int) (congestion * 100),
        closures > 0 ? "SÍ" : "No reportados",
        addresses,
        clientNotes.isEmpty() ? "" : "NOTAS DE CLIENTES:\n" + clientNotes);

    String fallback = generatePreRouteFallback(congestion, urgentOrders, hour);
    log.info("Consultando Gemini para recomendación pre-ruta del lote #{}", batch.getId());

    return geminiClient.generateText(prompt, fallback);
  }

  /**
   * CASO B — Desvío: Genera instrucción cuando el repartidor se desvía de la
   * ruta.
   *
   * @param nombreRepartidor Nombre del repartidor
   * @param distanciaDesvio  Distancia en metros desde la ruta planificada
   * @param siguienteParada  Dirección de la siguiente parada
   * @param ciudad           Ciudad actual
   * @return Instrucción natural para retomar la ruta
   */
  public String generateDeviationInstruction(String driverName, double deviationDistance,
      String nextStop, String city) {
    String prompt = String.format("""
        Eres el copiloto de logística de VibeRoute Colombia. El repartidor %s está actualmente a
        %.0f metros de su parada planificada en %s.

        Siguiente parada planificada: %s

        INSTRUCCIONES DE TONO:
        1. Sé sugerente, amable y profesional.
        2. Pregunta si todo está bien o si hay algún cierre vial u obstáculo no reportado.
        3. Recuérdele de forma motivadora que lo ideal es seguir la ruta para cumplir los tiempos.
        4. NO seas autoritario ni regañes.
        5. Responde en español colombiano. Máximo 2 oraciones. NO uses emojis.
        """,
        driverName,
        deviationDistance,
        city,
        nextStop);

    String fallback = String.format(
        "¿Todo bien, %s? Veo que estás a %.0fm de la ruta hacia %s. ¿Hay algún cierre en la vía o necesitas apoyo para retomar el camino?",
        driverName, deviationDistance, nextStop);

    log.info("Consultando Gemini para alerta sugerente de desvío de '{}'", driverName);
    return geminiClient.generateText(prompt, fallback);
  }

  /**
   * CASO C — Resumen: Genera resumen de la jornada de entregas.
   *
   * @param totalEntregados  Total de pedidos entregados
   * @param totalPendientes  Total de pedidos que quedaron pendientes
   * @param tiempoTotalHoras Horas totales de la jornada
   * @param ciudad           Ciudad de operación
   * @return Resumen en lenguaje natural
   */
  public String generateDailySummary(int totalDelivered, int totalPending,
      double totalHours, String city) {
    String prompt = String.format("""
        Eres el asistente logístico de VibeRoute Colombia. Genera un resumen BREVE de la jornada:

        - Ciudad: %s
        - Pedidos entregados: %d
        - Pedidos pendientes: %d
        - Tiempo total: %.1f horas

        Genera un resumen de 2-3 oraciones evaluando el rendimiento y sugiriendo mejoras.
        Responde en español colombiano. NO uses emojis.
        """,
        city, totalDelivered, totalPending, totalHours);

    String fallback = String.format(
        "Jornada en %s: %d pedidos entregados, %d pendientes en %.1f horas. %s",
        city, totalDelivered, totalPending, totalHours,
        totalPending == 0 ? "Excelente rendimiento." : "Se recomienda optimizar las rutas para reducir pendientes.");

    return geminiClient.generateText(prompt, fallback);
  }

  /**
   * Fallback inteligente cuando Gemini no está disponible.
   * Genera una recomendación basada en reglas simples.
   */
  private String generatePreRouteFallback(double congestion, long urgentOrders, String hour) {
    StringBuilder sb = new StringBuilder();

    if (congestion > 0.4) {
      sb.append("Congestión alta detectada. Se recomienda iniciar la ruta 15 minutos después o usar vías alternas. ");
    } else if (congestion > 0.2) {
      sb.append("Tráfico moderado. Rutas principales viables pero considere vías secundarias. ");
    } else {
      sb.append("Condiciones de tráfico favorables para iniciar la ruta de inmediato. ");
    }

    if (urgentOrders > 0) {
      sb.append(String.format("Hay %d pedido(s) de alta prioridad que deben entregarse primero.", urgentOrders));
    }

    return sb.toString().trim();
  }
}
