package com.routeoptimizer.service;
 
import com.routeoptimizer.external.GeminiClient;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import com.routeoptimizer.model.entity.Batch;
import com.routeoptimizer.model.entity.Order;

import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * Asesor Contextual Inteligente — el "Estratega" del sistema.
 * 
 * Orquesta prompts para Google Gemini según 3 casos de uso:
 * 1. Pre-ruta: Analiza lote + tráfico → genera recomendación de ruta
 * 2. Desvío: Detecta desviación → genera instrucción para retomar ruta
 * 3. Resumen: Analiza jornada → genera resumen del día
 */
@Service
public class ContextualAdvisor {

  private static final Logger log = LoggerFactory.getLogger(ContextualAdvisor.class);
  private final GeminiClient geminiClient;

  public ContextualAdvisor(GeminiClient geminiClient) {
    this.geminiClient = geminiClient;
  }

  /**
   * CASE A — Pre-route: Generates an intelligent recommendation BEFORE the driver
   * leaves.
   * Analyzes the complete batch context: number of orders, zone, traffic,
   * client notes and time of day.
   *
   * @param batch        The batch of orders to analyze
   * @param trafficData  Real-time traffic data from MLModelAdapter
   * @param urgentOrders Number of orders marked as high-priority
   * @return Natural language recommendation generated by Gemini
   */
  public String generatePreRouteRecommendation(Batch batch, Map<String, Double> trafficData, long urgentOrders) {
    List<Order> orders = batch.getOrders();
    String hour = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm"));
    double congestion = trafficData.getOrDefault("congestion_factor", 0.0);
    double closures = trafficData.getOrDefault("road_closures", 0.0);

    String city = orders.stream()
        .filter(p -> p.getCity() != null)
        .map(Order::getCity)
        .findFirst()
        .orElse("Bogotá");

    String addresses = orders.stream()
        .limit(5)
        .map(p -> String.format("- %s (%s, priority: %s)",
            p.getAddress(), p.getCity(), p.getPriority()))
        .collect(Collectors.joining("\n"));

    String clientNotes = orders.stream()
        .filter(p -> p.getClientReference() != null && !p.getClientReference().isBlank())
        .limit(3)
        .map(p -> String.format("- Order #%d (%s): \"%s\"", p.getId(), p.getAddress(), p.getClientReference()))
        .collect(Collectors.joining("\n"));

    String prompt = String.format("""
        Eres el asistente logístico de VibeRoute Colombia. Analiza este lote de entregas y genera
        una recomendación CORTA (máximo 3 oraciones) para el repartidor.

        CONTEXTO:
        - Ciudad: %s
        - Hora actual: %s
        - Total de pedidos: %d
        - Pedidos urgentes (prioridad ALTA): %d
        - Factor de congestión: %d%% (0%% = sin tráfico, 100%% = tráfico total)
        - Cierres viales reportados: %s

        PRIMERAS DIRECCIONES DEL LOTE:
        %s

        %s

        Responde en español colombiano, de forma profesional y directa.
        NO uses emojis. NO repitas los datos que te di. Solo da la recomendación.
        """,
        city,
        hour,
        orders.size(),
        urgentOrders,
        (int) (congestion * 100),
        closures > 0 ? "SÍ" : "No reportados",
        addresses,
        clientNotes.isEmpty() ? "" : "NOTAS DE CLIENTES:\n" + clientNotes);

    String fallback = generatePreRouteFallback(congestion, urgentOrders, hour);
    log.info("Consultando Gemini para recomendación pre-ruta del lote #{}", batch.getId());

    return geminiClient.generateText(prompt, fallback);
  }

  /**
   * CASO B — Desvío: Genera instrucción cuando el repartidor se desvía de la
   * ruta.
   *
   * @param nombreRepartidor Nombre del repartidor
   * @param distanciaDesvio  Distancia en metros desde la ruta planificada
   * @param siguienteParada  Dirección de la siguiente parada
   * @param ciudad           Ciudad actual
   * @return Instrucción natural para retomar la ruta
   */
  public String generateDeviationInstruction(String driverName, double deviationDistance,
      String nextStop, String city) {
    String prompt = String.format("""
        Eres el copiloto de logística de VibeRoute Colombia. El repartidor %s está actualmente a
        %.0f metros de su parada planificada en %s.

        Siguiente parada planificada: %s

        INSTRUCCIONES DE TONO:
        1. Sé sugerente, amable y profesional.
        2. Pregunta si todo está bien o si hay algún cierre vial u obstáculo no reportado.
        3. Recuérdele de forma motivadora que lo ideal es seguir la ruta para cumplir los tiempos.
        4. NO seas autoritario ni regañes.
        5. Responde en español colombiano. Máximo 2 oraciones. NO uses emojis.
        """,
        driverName,
        deviationDistance,
        city,
        nextStop);

    String fallback = String.format(
        "¿Todo bien, %s? Veo que estás a %.0fm de la ruta hacia %s. ¿Hay algún cierre en la vía o necesitas apoyo para retomar el camino?",
        driverName, deviationDistance, nextStop);

    log.info("Consultando Gemini para alerta sugerente de desvío de '{}'", driverName);
    return geminiClient.generateText(prompt, fallback);
  }

  /**
   * CASO C — Resumen: Genera resumen de la jornada de entregas.
   *
   * @param totalDelivered   Total de pedidos entregados
   * @param totalPending     Total de pedidos que quedaron pendientes
   * @param totalCancelled   Total de pedidos cancelados
   * @param totalReturned    Total de pedidos devueltos
   * @param efficiencyScore  Puntuación de eficiencia calculada
   * @param totalHours       Horas totales de la jornada
   * @param city             Ciudad de operación
   * @return Resumen en lenguaje natural
   */
  public String generateDailySummary(int totalDelivered, int totalPending,
      int totalCancelled, int totalReturned, int efficiencyScore,
      double totalHours, String city) {
    String prompt = String.format("""
        Eres el asistente logístico de VibeRoute Colombia. Escribe un resumen ESTRICTO de la jornada exactamente con esta estructura y tono:

        "Buenas tardes, equipo. Aquí va el resumen de la jornada de hoy en %s: Hoy en %s, la jornada de VibeRoute culminó con %d pedidos entregados, %d cancelado(s) y %d devuelto(s), dejando %d pendientes en un tiempo total de %.1f horas. El score de eficiencia fue del %d%%. [Añade aquí 1-2 oraciones analizando si el score es bueno o malo dependiendo de la tasa de cancelaciones/devoluciones y da una sugerencia logística directa. Por ejemplo: 'Si bien el tiempo de operación fue corto, la alta tasa de cancelaciones...']"

        Reglas estrictas:
        - Debes iniciar EXACTAMENTE con "Buenas tardes, equipo."
        - Responde en español colombiano profesional.
        - NO uses emojis.
        - NO menciones que eres una IA.
        - Solo completa el corchete con el análisis.
        """,
        city, city, totalDelivered, totalCancelled, totalReturned, totalPending, totalHours, efficiencyScore);

    String fallback = String.format(
        "Buenas tardes, equipo. Aquí va el resumen de la jornada de hoy en %s: Hoy en %s, la jornada de VibeRoute culminó con %d pedidos entregados, %d cancelado(s) y %d devuelto(s), dejando %d pendientes en un tiempo total de %.1f horas. El score de eficiencia fue del %d%%. %s",
        city, city, totalDelivered, totalCancelled, totalReturned, totalPending, totalHours, efficiencyScore,
        efficiencyScore >= 80 ? "Excelente rendimiento, mantengan el buen trabajo." : "Es crucial investigar las causas raíz de estas novedades para mejorar la tasa de éxito.");

    return geminiClient.generateText(prompt, fallback);
  }

  /**
   * Fallback inteligente cuando Gemini no está disponible.
   * Genera una recomendación basada en reglas simples.
   */
  private String generatePreRouteFallback(double congestion, long urgentOrders, String hour) {
    StringBuilder sb = new StringBuilder();

    if (congestion > 0.4) {
      sb.append("Congestión alta detectada. Se recomienda iniciar la ruta 15 minutos después o usar vías alternas. ");
    } else if (congestion > 0.2) {
      sb.append("Tráfico moderado. Rutas principales viables pero considere vías secundarias. ");
    } else {
      sb.append("Condiciones de tráfico favorables para iniciar la ruta de inmediato. ");
    }

    if (urgentOrders > 0) {
      sb.append(String.format("Hay %d pedido(s) de alta prioridad que deben entregarse primero.", urgentOrders));
    }

    return sb.toString().trim();
  }

  /**
   * Generates text directly from a dynamic prompt.
   */
  public String askGeminiDirect(String prompt) {
      return geminiClient.generateText(prompt, "Reporte Automático: Zonas geográficas optimizadas para los pedidos actuales.");
  }

  /**
   * CASE D — Copilot: Generates progressive delivery tips for the driver.
   * 
   * Single Gemini call produces a JSON array with 5-7 contextual tips,
   * each tagged with a trigger condition (Strategy Pattern labels).
   * Tips are cached in Batch.aiCopilotTips to avoid repeated API calls.
   *
   * @param batch      The batch with orders to analyze
   * @param driverName The name of the assigned driver
   * @return JSON array string of tips, or a default fallback
   */
  public String generateBatchCopilotTips(Batch batch, String driverName) {
    List<Order> orders = batch.getOrders();
    String hour = LocalTime.now().format(DateTimeFormatter.ofPattern("HH:mm"));

    String city = orders.stream()
        .filter(o -> o.getCity() != null)
        .map(Order::getCity)
        .findFirst()
        .orElse("Colombia");

    long highPriorityCount = orders.stream()
        .filter(o -> o.getPriority() != null && "HIGH".equalsIgnoreCase(o.getPriority().name()))
        .count();

    String highAddresses = orders.stream()
        .filter(o -> o.getPriority() != null && "HIGH".equalsIgnoreCase(o.getPriority().name()))
        .limit(3)
        .map(Order::getAddress)
        .collect(Collectors.joining(", "));

    long missingNameCount = orders.stream()
        .filter(o -> o.getClientName() == null || o.getClientName().isBlank())
        .count();

    long missingPriceCount = orders.stream()
        .filter(o -> o.getPrice() == null || o.getPrice().doubleValue() <= 0)
        .count();

    String prompt = String.format("""
        You are VibeRoute Colombia's intelligent delivery copilot. Generate a JSON array 
        with exactly 6 short spoken suggestions for driver %s delivering %d orders in %s.

        BATCH CONTEXT:
        - HIGH priority orders: %d → %s
        - Orders missing client name: %d
        - Orders missing price: %d
        - Departure time: %s

        RESPONSE FORMAT (JSON array only, no explanation):
        [{"message":"short phrase in Colombian Spanish","trigger":"ON_START","priority":"HIGH"}]

        VALID TRIGGERS (use each at least once):
        - ON_START: when starting the route
        - AFTER_DELIVERY_3: after the 3rd delivery
        - HALFWAY: at the halfway point
        - NEAR_END: when 2 orders remain
        - ALL_DONE: when all deliveries are complete
        - GENERAL: can be shown at any point

        TONE RULES:
        - Speak like a friendly colleague: "Hey %s, remember that..."
        - NO emojis. Max 20 words per message.
        - Colombian Spanish. Professional but warm.
        - If there are HIGH priority orders, ON_START must mention them.
        - If there are orders without client name, include a caution tip.
        """,
        driverName, orders.size(), city,
        highPriorityCount, highAddresses.isEmpty() ? "none" : highAddresses,
        missingNameCount, missingPriceCount, hour, driverName);

    String fallback = generateCopilotFallback(driverName, orders.size(), highPriorityCount);

    log.info("Generating copilot tips for batch #{} (driver: {}, {} orders)", 
        batch.getId(), driverName, orders.size());

    return geminiClient.generateText(prompt, fallback);
  }

  /**
   * Fallback copilot tips when Gemini is unavailable.
   * Returns a valid JSON array with generic but useful tips.
   */
  private String generateCopilotFallback(String driverName, int totalOrders, long highCount) {
    String highTip = highCount > 0
        ? String.format("Tienes %d pedido(s) de alta prioridad, arranca con esos", highCount)
        : "Revisa tu lista y arranca con la primera entrega";

    return String.format("""
        [
          {"message":"%s, %s","trigger":"ON_START","priority":"HIGH"},
          {"message":"Vas bien, ya llevas 3 entregas. Sigue con ese ritmo","trigger":"AFTER_DELIVERY_3","priority":"LOW"},
          {"message":"Mitad de ruta completada, buen avance %s","trigger":"HALFWAY","priority":"LOW"},
          {"message":"Quedan solo 2 entregas, ya casi terminas","trigger":"NEAR_END","priority":"MEDIUM"},
          {"message":"Excelente trabajo %s, jornada completada","trigger":"ALL_DONE","priority":"LOW"},
          {"message":"Verifica la dirección antes de cada entrega para evitar devoluciones","trigger":"GENERAL","priority":"MEDIUM"}
        ]""", driverName, highTip, driverName, driverName);
  }
}
